name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or 'master' if that's your default
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Blazor WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Blazor WebAssembly
        run: |
          cd Client             # 🔁 Change this if your Blazor project folder is different
          dotnet publish -c Release -o build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.Digitax_App1_SPN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Client"                   # 🔁 Your Blazor folder name
          output_location: "Client/build/wwwroot"  # Blazor static output
          deployment_environment: "production"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Close Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.Digitax_App1_SPN }}
          action: close
          repo_token: ${{ secrets.GITHUB_TOKEN }}
